### ISSUE TITLE
Can't run as cargo subcommand

### ISSUE THREAD

**Issue by dimtpap** [cat-in-136/cargo-generate-rpm#114]
Running as a Cargo subcommand always fails
```sh
$ cargo generate-rpm  
error: The following required argument was not provided: auto_req
```
whereas directly running the executable
```sh
$ cargo-generate-rpm
```
runs normally.

This is the case even in a fresh Cargo project (`cargo new --bin ./gen-rpm-test`) with this simple `Cargo.toml`
```toml
[package]
name = "gen-rpm-test"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "test"

[dependencies]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/gen-rpm-test", dest = "/usr/bin/gen-rpm-test", mode = "755" }
]
```
