### ISSUE TITLE
Empty dependencies added to package

### ISSUE THREAD

**Issue by dmulder** [cat-in-136/cargo-generate-rpm#131]
I have the following Cargo.toml:

```toml
[package]
name = "qr-greeter"
version.workspace = true
authors.workspace = true
description = "GNOME Shell extension that adds a QR code to authentication prompts when a MS DAG URL is detected."
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[package.metadata.deb]
name = "himmelblau-qr-greeter"
depends = ["gnome-shell"]
assets = [
  ["src/qr-greeter@himmelblau-idm.org/extension.js", "usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/extension.js", "644"],
  ["src/qr-greeter@himmelblau-idm.org/metadata.json", "usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/metadata.json", "644"],
  ["src/qr-greeter@himmelblau-idm.org/stylesheet.css", "usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/stylesheet.css", "644"],
  ["src/msdag.png", "usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/msdag.png", "644"],
]

[package.metadata.generate-rpm]
name = "himmelblau-qr-greeter"
assets = [
  { source = "src/qr-greeter@himmelblau-idm.org/extension.js", dest = "/usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/extension.js", mode = "644" },
  { source = "src/qr-greeter@himmelblau-idm.org/metadata.json", dest = "/usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/metadata.json", mode = "644" },
  { source = "src/qr-greeter@himmelblau-idm.org/stylesheet.css", dest = "/usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/stylesheet.css", mode = "644" },
  { source = "src/msdag.png", dest = "/usr/share/gnome-shell/extensions/qr-greeter@himmelblau-idm.org/msdag.png", mode = "644" },
]
requires = ["gnome-shell"]
```

This is part of the himmelblau project. The package generated by this toml has 'blank' dependencies:

```sh
> rpm -qpR himmelblau-qr-greeter-1.0.0-1.x86_64-sle15sp6.rpm 
/bin/sh
gnome-shell

rpmlib(CompressedFileNames) = 3.0.4-1
rpmlib(FileDigests) = 4.6.0-1
rpmlib(PayloadFilesHavePrefix) = 4.0-1
rpmlib(PayloadIsZstd) = 5.4.18-1
```

Notice the extra blank line in the deps?

```sh
> sudo zypper in himmelblau-qr-greeter-1.0.0-1.x86_64-sle15sp6.rpm
[sudo] password for root: 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: 1: nothing provides '' needed by the to be installed himmelblau-qr-greeter-1.0.0-1.x86_64
 Solution 1: do not install himmelblau-qr-greeter-1.0.0-1.x86_64
 Solution 2: break himmelblau-qr-greeter-1.0.0-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

I also tried with this syntax:

```toml
[package.metadata.generate-rpm.requires]
gnome-shell = "*"
```

But that does the same thing. It looks like a bug in the way the rpm spec is being generated.
