### ISSUE TITLE
Add support for workspace inheritance for version and other properties

### ISSUE THREAD

**Issue by Christiaan676** [cat-in-136/cargo-generate-rpm#44]
Rust [1.64](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds) added support for [workspace inheritance ](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacepackage-table) making it possible to inherit the version and other properties from the workspace.toml.

```
# [PROJECT_DIR]/Cargo.toml
[workspace]
members = ["bar"]

[workspace.package]
version = "1.2.3"
authors = ["Nice Folks"]
description = "A short description of my package"
documentation = "https://example.com/bar"
```

```
# [PROJECT_DIR]/bar/Cargo.toml
[package]
name = "bar"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
```

Unfortunately cargo-generate-rpm currently does not support these.

**Comment by cat-in-136** [comment]
@gilescope  you said "Just bump **toml_edit** " but bumping **cargo_toml** seems to be correct.

**Comment by Christiaan676** [comment]
@cat-in-136 Thanks for updating and releasing a new version. Unfortunately trying it out on my project fails with the following error:
```
$ cargo generate-rpm --payload-compress none -p bin
/usr/local/cargo/bin/cargo-generate-rpm: Cargo.toml: value from workspace hasn't been set
```

Project layout looks like:
```
\
   \bin
      \src
      Cargo.toml
   <Some other projects in workspace>
   Cargo.toml
```
The workspace toml has the version, edition, license set. And in project project has the matching `workspace = true`. The cargo command is executed from the workspace dir.

**Comment by cat-in-136** [comment]
@Christiaan676 It's up to your cargo.toml

I've confirmed it with following tiny workspace.

/foo/Cargo.toml
```toml
[workspace]
members = ["bar"]

[workspace.package]
version = "1.2.3"
authors = ["Nice Folks"]
license = "MIT"
description = "A short description of my package"
documentation = "https://example.com/bar"
```

/foo/bar/Cargo.toml
```toml
[package]
name = "bar"
version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
documentation.workspace = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/bar", dest = "/usr/bin/bar", mode = "0755" }
]
```

/foo/bar/src/main.rs
```rust
fn main() {
    println!("Hello, world!");
}
```

I hope this will be of help to you.

Execute under workspace directory (/foo)
```console
$ cargo build ---release
$ cargo-generate-rpm -p bar
```
